name = "my-new-func"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "my-new-func_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "my-new-func.wasm"
command = "npm run build:release"
